services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - financecore-network

  migrator:
    build:
      context: .
      dockerfile: FinanceCore.Database/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__FinanceCore: "Server=sqlserver;Database=FinanceCore;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
    networks:
      - financecore-network

  api:
    build:
      context: .
    depends_on:
      sqlserver:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      Serilog__WriteTo__1__Args__serverUrl: "${SEQ_SERVER_URL}"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=FinanceCore;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
    networks:
      - financecore-network

  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: "${SEQ_ADMIN_USERNAME}"
      SEQ_FIRSTRUN_ADMINPASSWORD: "${SEQ_ADMIN_PASSWORD}"
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    networks:
      - financecore-network

networks:
  financecore-network:
    driver: bridge

volumes:
  sqlserver-data:
  seq-data:
