
CREATE TABLE UserRoles(
	Id INT PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
);

INSERT INTO UserRoles (Id,Name) VALUES(0,'User');
INSERT INTO UserRoles (Id,Name) VALUES(1,'Admin');

ALTER TABLE Users
ADD Role INT NOT NULL
   CONSTRAINT DF_Users_Role DEFAULT 0;
ALTER TABLE Users
ADD CONSTRAINT FK_UserRoles FOREIGN KEY (Role) REFERENCES UserRoles(Id); 

