CREATE TABLE Batches (

	Id UNIQUEIDENTIFIER PRIMARY KEY,
	AccountId UNIQUEIDENTIFIER NOT NULL,
	FileName NVARCHAR(255) NOT NULL,
	ImportedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	TransactionCount INT NOT NULL,

	CONSTRAINT FK_Batches_AccountId 
		FOREIGN KEY (AccountId)
			REFERENCES Accounts(Id)
);

ALTER TABLE Transactions 
	ADD BatchId UNIQUEIDENTIFIER NULL;

ALTER TABLE Transactions
	ADD CONSTRAINT FK_Transaction_BatchId FOREIGN KEY (BatchId) REFERENCES Batches(Id);